CREATE TABLE TB_INFO(
  INFO_NO NUMBER(3) NOT NULL,
  PC_NO VARCHAR2(10) UNIQUE NOT NULL,
  NM VARCHAR2(20) ,
  EMAIL VARCHAR2(50),
  HOBBY VARCHAR2(1000),
  MBTI VARCHAR2(4)
  );
  
  SELECT *
  FROM TB_INFO
  WHERE MBTI = 'ESTJ'  
  OR MBTI = 'ISTJ'
  ORDER BY MBTI DESC;
  
